### ISSUE TITLE
Port to Datapack or Server Plugin

### ISSUE THREAD

**Issue by Adi-0** [Trikzon/flourish#12]
Hi! Thanks for this mod and the effort you put into this mod, its awesome!

By any chance, would it be possible to create a datapack or plugin that achieves this same purpose? I am not that familiar with minecraft modding to know, but if it is convenient to do so it would be awesome. (There used to be a spigot plugin like this called "flower-meal", but its outdated sadly)

If it requires extra time or too much work, no sweat about it! This was just a request in the off chance it is easy to pull off.

Anyway, thank you either way in advance and have an awesome day!

**Comment by Trikzon** [comment]
Thanks for your interest in the mod!

Unfortunately I've never developed a plugin or datapack before. I'd have to learn all the specifics of each and that would take a long time. If someone else wants to they can with appropriate credit (as the MIT license states)

For now, however, I'm going to only be developing this for forge/fabric (Actually, you can expect a 1.17.1 and 1.18.1 update in the next day or 2).

**Comment by Adi-0** [comment]
Oh man hey its been a while but I dont think I ever realized that I got a response on this haha, albeit late, many thanks for the reply!

**Comment by Trikzon** [comment]
The license of Flourish for newer versions was changed to LGPL v3. Another developer can still port this if they would like, but they would have to follow the new license (if they port the new code). 

Since this likely won't be happening, I am closing this issue as not planned
