### ISSUE TITLE
[Suggestion] Disable Torch Flower spreading by default

### ISSUE THREAD

**Issue by DJChaos42** [Trikzon/flourish#13]
Like Wither Roses, Torch Flowers aren't meant to be easily obtainable. Therefore their ability to spread should also be set to false in the config by default.

**Comment by Trikzon** [comment]
What mod adds torch flowers?

**Comment by DJChaos42** [comment]
Torch Flowers are part of vanilla 1.20

**Comment by Trikzon** [comment]
Oh... Wow, I really don't follow the updates that closely anymore xD. Yep, I'll make that change soon

**Comment by Trikzon** [comment]
Fixed in v2.2.0-1.20
