### ISSUE TITLE
Server side support?

### ISSUE THREAD

**Issue by CodeAsm** [Trikzon/flourish#16]
I tried adding the plugin to my server but it finds it uncompatible.
Now, your github does not mention it anywhere nor does your descirbtion on the https://modrinth.com/mod/flourish/versions site.

But under the left colum, it does state:  Client and server DecorationGame MechanicsUtility

Which I may have mistaked for server support. Or am I reading their site wrong? Feel free to answer and close the issue if its completly my mistake. if its a sites design issue and users just randomly enable server too, close my issue aswell but Id like the answer.

If you want to support server side :D that be awesome. (I have bedrock players join my java server using geysermc) and I also started missing the bonemeal your flowers mechanic while playing in minecraft, on bedrock this is so normal, I just dunno how to mod non java players, Ican install your plugin on my clients, but the bedrock clients cant XD

Thank you for reading and making this awesome plugin. have a wonderful day

**Comment by Trikzon** [comment]
The mod is supposed to support servers, but tbh I have not tested it in a couple years. I'll test it out and report back

**Comment by CodeAsm** [comment]
Ok, yes it works on a fabric based server, while i was using paper.
https://fabricmc.net/use/server/

```afaik fabric mods aren't compatilbe with paper, you need the mod both client and server side```@grain on your discord server saw what my "mistake" was.
https://discord.com/channels/450018397657235460/1086162797181808640/1253678969371361362

Current mods list works fine on the fabric server, for those who stumble upon this, and your mods may not be compatible, try look for "Cardboard", it may help run paper mods on fabric. Closing, as this is not an issue if choosing servers and mods correctly
