### ISSUE TITLE
1.21

### ISSUE THREAD

**Issue by Fire-Horse27** [Trikzon/flourish#17]
Will this be updated to 1.21? I love this mod and would hate to see development stop!

**Comment by Trikzon** [comment]
It will be. I just haven't gotten around to it yet. Thank you for liking the mod :)

**Comment by Fire-Horse27** [comment]
Great! I will be looking forward to it!

**Comment by Trikzon** [comment]
The 1.21 update is now available [here](https://modrinth.com/mod/flourish/versions) :)
