### ISSUE TITLE
Causing CTD with Dispensers on trees

### ISSUE THREAD

**Issue by Phicksur** [Trikzon/flourish#4]
On a server, I had set up a dispenser with bonemeal to grow oak trees, but when the dispenser tried to use bonemeal on the tree after it had grown up, it caused a CTD that prevented me from logging back into the game without it crashing.

After disabling your mod, and only your mod, it resolved the issue.

**Comment by Trikzon** [comment]
What is a CTD?

**Comment by Phicksur** [comment]
Crash To Desktop.
Wholesale crash.
It kills the server deadified.
It brokedededed.
:)

**Comment by Trikzon** [comment]
Did it make a crash report?

**Comment by Trikzon** [comment]
Also, what version and forge or fabric?

**Comment by Phicksur** [comment]
Fabric
Crash report may have been generated, but I have since rebuilt the server and wiped the old files.

**Comment by Trikzon** [comment]
I'll put it on my list of things to do soon: test this on a server.

If I can't replicate the crash, I can't fix it without a crash report

**Comment by Trikzon** [comment]
@Phicksur Could you test this with the new version just published, v1.3.0? I believe it should be fixed.

**Comment by Trikzon** [comment]
Closed because it seems to be fixed by v1.3.0.
